# Generated by Django 5.2.6 on 2025-09-17 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passwords', '0002_userencryptionprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passwordentry',
            options={'ordering': ['category__name', 'service_name', 'username']},
        ),
        migrations.RemoveField(
            model_name='passwordentry',
            name='encrypted_data',
        ),
        migrations.AddField(
            model_name='passwordentry',
            name='comments',
            field=models.TextField(blank=True, help_text='Optional additional notes or comments'),
        ),
        migrations.AddField(
            model_name='passwordentry',
            name='encrypted_password',
            field=models.TextField(default='', help_text='Encrypted password'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='passwordentry',
            name='service_name',
            field=models.CharField(default='', help_text='Name of the service/website', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='passwordentry',
            name='username',
            field=models.CharField(default='', help_text='Username/email for the service', max_length=200),
            preserve_default=False,
        ),
    ]
