# Generated by Django 5.2.6 on 2025-09-17 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passwords', '0003_alter_passwordentry_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordentry',
            name='service_url',
            field=models.URLField(blank=True, help_text='Optional URL for the service/website'),
        ),
    ]
